### ISSUE TITLE
Optional dependencies?

### ISSUE THREAD

**Issue by the-database** [kleisauke/pyvips-binary#1]
Hi, thanks for this project, it makes it much easier to get pyvips API mode running on Windows. 

I tried to load a jxl image but got a `VipsForeignLoad: ... is not a known file format` error. I believe that means the optional dependency for libjxl was not installed while compiling? Would it be possible to include the optional dependencies, or are they being excluded intentionally?

**Comment by kleisauke** [comment]
Please subscribe to https://github.com/libvips/build-win64-mxe/issues/40 for possible updates regarding JPEG XL support within the prebuilt Windows binaries.
